/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  contracts: [{ type: 'autogenerated', dirName: 'contracts' }],
  sdk: [{ type: 'autogenerated', dirName: 'sdk' }],
};

module.exports = sidebars;
